version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x64
- Win32

before_build:
  - mkdir include\kytea
  - copy src\include\kytea\kytea.h include\kytea\
  - copy src\include\kytea\kytea-string.h include\kytea\
build:
  project: build-win\kytea.sln
  parallel: true
  verbosity: minimal

after_build:
    - set PLATFORM_PREFIX=
    - if "%PLATFORM%"=="x64" set PLATFORM_PREFIX="64"
    - cd %APPVEYOR_BUILD_FOLDER%\
    - 7z a kytea-win-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\build-win\build-win\Release%PLATFORM_PREFIX%\kytea.exe
    - 7z a kytea-win-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\build-win\build-win\Release%PLATFORM_PREFIX%\train-kytea.exe
    - 7z a kytea-win-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\build-win\build-win\Release%PLATFORM_PREFIX%\lib
    - 7z a kytea-win-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\include

artifacts:
- path: '*.zip'
  name: kytea-win
deploy:
  description: 'kytea-win'
  provider: GitHub
  auth_token:
    secure: WcAHkON2wIKV1F/fwpQgUsk45iZilZfIb+9dIxX0GnneMFCdal/8FpM8gZmPO/N4
  artifact: kytea-win
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
